### ISSUE TITLE
Won't launch on Java SE 11.x.x

### ISSUE THREAD

**Issue by adakac** [Zahlii/Advanced-Youtube-Downloader#2]
The following error gets returned, seems like Java 11 doesn't support the Substance UI-Theme.
My Java Version:
```
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```

Error Output on `java -jar .\advancedyoutubedownload.jar`:
```
java.exe -jar .\advancedyoutubedownload.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/pushingpixels/substance/api/skin/SubstanceGraphiteGlassLookAndFeel
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.pushingpixels.substance.api.skin.SubstanceGraphiteGlassLookAndFeel
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more
```

**Comment by FRUEHNI1** [comment]
Can you test whether this is definitely an issue with the java version by switching to an older java version manually and re-testing?

If it is, I guess the easiest way is to remove the look and feel.

**Comment by Zahlii** [comment]
Can you test whether this is definitely an issue with the java version by switching to an older java version manually and re-testing?

If it is, I guess the easiest way is to remove the look and feel.
